name       : gnuradio
version    : 3.9.0.0
release    : 3
source     :
    - https://github.com/gnuradio/gnuradio/releases/download/v3.9.0.0/gnuradio-3.9.0.0.tar.xz : 0a2622933c96a4b22405c7656b8af0db32762834317ec2b90bff0a0a5a4f75cb
license    : GPL-3.0-or-later
homepage   : https://www.gnuradio.org
component  : network.remote
summary    : Extensive Radio Ecosystem
description: |
    GNU Radio is a free & open-source software development toolkit that provides signal processing blocks to implement software radios
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(fftw3)
    - pkgconfig(python3)
    - pkgconfig(log4cpp)
    - pkgconfig(Qt5Core)
    - pkgconfig(alsa)
    - pkgconfig(gsl)
    - pkgconfig(libzmq)
    - pkgconfig(sdl)
    - pkgconfig(sndfile)
    - pkgconfig(volk)
    - cppzmq
    - libboost-devel
    - mako
    - numpy
    - pybind11
    - python3-cairo
    - python3-qt5
    - python-cheetah
    - python-gobject
    - python-lxml
    - qwt-devel
    - swig
rundeps    :
    - numpy
    - python3-cairo
    - python-lxml
    - python-gobject
    - python-pyzmq
    - swig
    - scipy
setup      : |
    sed -i '58s/.*/set(GR_MAKO_MIN_VERSION "0.4.2")/' CMakeLists.txt
    %cmake_ninja -DPYTHON_EXECUTABLE=/usr/bin/python3.9 -DCMAKE_INSTALL_PREFIX=/usr
build      : |
    %ninja_build
install    : |
    %ninja_install
